//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package client.proizvajalec;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ManageProizvajalecExport1_ManageProizvajalecHttpService", targetNamespace = "http://KISFoodLib/ManageProizvajalec", wsdlLocation = "WEB-INF/wsdl/KISFood_ManageProizvajalecExport1.wsdl")
public class ManageProizvajalecExport1ManageProizvajalecHttpService
    extends Service
{

    private final static URL MANAGEPROIZVAJALECEXPORT1MANAGEPROIZVAJALECHTTPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.proizvajalec.ManageProizvajalecExport1ManageProizvajalecHttpService.class.getName());

    static {
        URL url = null;
        try {
            url = client.proizvajalec.ManageProizvajalecExport1ManageProizvajalecHttpService.class.getResource("/WEB-INF/wsdl/KISFood_ManageProizvajalecExport1.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/KISFood_ManageProizvajalecExport1.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/KISFood_ManageProizvajalecExport1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANAGEPROIZVAJALECEXPORT1MANAGEPROIZVAJALECHTTPSERVICE_WSDL_LOCATION = url;
    }

    public ManageProizvajalecExport1ManageProizvajalecHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageProizvajalecExport1ManageProizvajalecHttpService() {
        super(MANAGEPROIZVAJALECEXPORT1MANAGEPROIZVAJALECHTTPSERVICE_WSDL_LOCATION, new QName("http://KISFoodLib/ManageProizvajalec", "ManageProizvajalecExport1_ManageProizvajalecHttpService"));
    }

    /**
     * 
     * @return
     *     returns ManageProizvajalec
     */
    @WebEndpoint(name = "ManageProizvajalecExport1_ManageProizvajalecHttpPort")
    public ManageProizvajalec getManageProizvajalecExport1ManageProizvajalecHttpPort() {
        return super.getPort(new QName("http://KISFoodLib/ManageProizvajalec", "ManageProizvajalecExport1_ManageProizvajalecHttpPort"), ManageProizvajalec.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageProizvajalec
     */
    @WebEndpoint(name = "ManageProizvajalecExport1_ManageProizvajalecHttpPort")
    public ManageProizvajalec getManageProizvajalecExport1ManageProizvajalecHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://KISFoodLib/ManageProizvajalec", "ManageProizvajalecExport1_ManageProizvajalecHttpPort"), ManageProizvajalec.class, features);
    }

}
