//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package client.proizvajalec;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ManageProizvajalec", targetNamespace = "http://KISFoodLib/ManageProizvajalec")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManageProizvajalec {


    /**
     * 
     * @param proizvajalec
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createProizvajalec", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.CreateProizvajalec")
    @ResponseWrapper(localName = "createProizvajalecResponse", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.CreateProizvajalecResponse")
    public Boolean createProizvajalec(
        @WebParam(name = "proizvajalec", targetNamespace = "")
        Proizvajalec proizvajalec);

    /**
     * 
     * @param id
     * @return
     *     returns client.proizvajalec.Proizvajalec
     */
    @WebMethod
    @WebResult(name = "proizvajalec", targetNamespace = "")
    @RequestWrapper(localName = "readProizvajalec", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.ReadProizvajalec")
    @ResponseWrapper(localName = "readProizvajalecResponse", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.ReadProizvajalecResponse")
    public Proizvajalec readProizvajalec(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param proizvajalec
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateProizvajalec", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.UpdateProizvajalec")
    @ResponseWrapper(localName = "updateProizvajalecResponse", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.UpdateProizvajalecResponse")
    public Boolean updateProizvajalec(
        @WebParam(name = "proizvajalec", targetNamespace = "")
        Proizvajalec proizvajalec);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteProizvajalec", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.DeleteProizvajalec")
    @ResponseWrapper(localName = "deleteProizvajalecResponse", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.DeleteProizvajalecResponse")
    public Boolean deleteProizvajalec(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns client.proizvajalec.Proizvajalci
     */
    @WebMethod
    @WebResult(name = "proizvajalci", targetNamespace = "")
    @RequestWrapper(localName = "listProizvajalec", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.ListProizvajalec")
    @ResponseWrapper(localName = "listProizvajalecResponse", targetNamespace = "http://KISFoodLib/ManageProizvajalec", className = "client.proizvajalec.ListProizvajalecResponse")
    public Proizvajalci listProizvajalec();

}
