//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package client.drzava;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ManageDrzavaExport1_ManageDrzavaHttpService", targetNamespace = "http://KISFoodLib/ManageDrzava", wsdlLocation = "WEB-INF/wsdl/KISFood_ManageDrzavaExport1.wsdl")
public class ManageDrzavaExport1ManageDrzavaHttpService
    extends Service
{

    private final static URL MANAGEDRZAVAEXPORT1MANAGEDRZAVAHTTPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.drzava.ManageDrzavaExport1ManageDrzavaHttpService.class.getName());

    static {
        URL url = null;
        try {
            url = client.drzava.ManageDrzavaExport1ManageDrzavaHttpService.class.getResource("/WEB-INF/wsdl/KISFood_ManageDrzavaExport1.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/KISFood_ManageDrzavaExport1.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/KISFood_ManageDrzavaExport1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANAGEDRZAVAEXPORT1MANAGEDRZAVAHTTPSERVICE_WSDL_LOCATION = url;
    }

    public ManageDrzavaExport1ManageDrzavaHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageDrzavaExport1ManageDrzavaHttpService() {
        super(MANAGEDRZAVAEXPORT1MANAGEDRZAVAHTTPSERVICE_WSDL_LOCATION, new QName("http://KISFoodLib/ManageDrzava", "ManageDrzavaExport1_ManageDrzavaHttpService"));
    }

    /**
     * 
     * @return
     *     returns ManageDrzava
     */
    @WebEndpoint(name = "ManageDrzavaExport1_ManageDrzavaHttpPort")
    public ManageDrzava getManageDrzavaExport1ManageDrzavaHttpPort() {
        return super.getPort(new QName("http://KISFoodLib/ManageDrzava", "ManageDrzavaExport1_ManageDrzavaHttpPort"), ManageDrzava.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageDrzava
     */
    @WebEndpoint(name = "ManageDrzavaExport1_ManageDrzavaHttpPort")
    public ManageDrzava getManageDrzavaExport1ManageDrzavaHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://KISFoodLib/ManageDrzava", "ManageDrzavaExport1_ManageDrzavaHttpPort"), ManageDrzava.class, features);
    }

}
