<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ManageProizvajalecExport1_ManageProizvajalecHttp_Service" targetNamespace="http://KISFoodLib/ManageProizvajalec" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://KISFoodLib/ManageProizvajalec" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="ManageProizvajalec.wsdl" namespace="http://KISFoodLib/ManageProizvajalec">
    </wsdl:import>
  <wsdl:binding name="ManageProizvajalecExport1_ManageProizvajalecHttpBinding" type="this:ManageProizvajalec">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="createProizvajalec">
      <soap:operation soapAction=""/>
      <wsdl:input name="createProizvajalecRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="createProizvajalecResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readProizvajalec">
      <soap:operation soapAction=""/>
      <wsdl:input name="readProizvajalecRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="readProizvajalecResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateProizvajalec">
      <soap:operation soapAction=""/>
      <wsdl:input name="updateProizvajalecRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateProizvajalecResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="deleteProizvajalec">
      <soap:operation soapAction=""/>
      <wsdl:input name="deleteProizvajalecRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="deleteProizvajalecResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listProizvajalec">
      <soap:operation soapAction=""/>
      <wsdl:input name="listProizvajalecRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listProizvajalecResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ManageProizvajalecExport1_ManageProizvajalecHttpService">
    <wsdl:port binding="this:ManageProizvajalecExport1_ManageProizvajalecHttpBinding" name="ManageProizvajalecExport1_ManageProizvajalecHttpPort">
      <soap:address location="http://localhost:9080/KISFoodWeb/sca/ManageProizvajalecExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>