//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client.kategorija;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ManageKategorija", targetNamespace = "http://KISFoodLib/ManageKategorija")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManageKategorija {


    /**
     * 
     * @param kategorija
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createKategorija", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.CreateKategorija")
    @ResponseWrapper(localName = "createKategorijaResponse", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.CreateKategorijaResponse")
    public Boolean createKategorija(
        @WebParam(name = "kategorija", targetNamespace = "")
        Kategorija kategorija);

    /**
     * 
     * @param id
     * @return
     *     returns foodratings.client.kategorija.Kategorija
     */
    @WebMethod
    @WebResult(name = "kategorija", targetNamespace = "")
    @RequestWrapper(localName = "readKategorija", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.ReadKategorija")
    @ResponseWrapper(localName = "readKategorijaResponse", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.ReadKategorijaResponse")
    public Kategorija readKategorija(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param kategorija
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateKategorija", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.UpdateKategorija")
    @ResponseWrapper(localName = "updateKategorijaResponse", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.UpdateKategorijaResponse")
    public Boolean updateKategorija(
        @WebParam(name = "kategorija", targetNamespace = "")
        Kategorija kategorija);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteKategorija", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.DeleteKategorija")
    @ResponseWrapper(localName = "deleteKategorijaResponse", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.DeleteKategorijaResponse")
    public Boolean deleteKategorija(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns foodratings.client.kategorija.Kategorije
     */
    @WebMethod
    @WebResult(name = "kategorije", targetNamespace = "")
    @RequestWrapper(localName = "listKategorija", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.ListKategorija")
    @ResponseWrapper(localName = "listKategorijaResponse", targetNamespace = "http://KISFoodLib/ManageKategorija", className = "foodratings.client.kategorija.ListKategorijaResponse")
    public Kategorije listKategorija();

}
