//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client.kategorija;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ManageKategorijaExport1_ManageKategorijaHttpService", targetNamespace = "http://KISFoodLib/ManageKategorija", wsdlLocation = "WEB-INF/wsdl/KISFood_ManageKategorijaExport1.wsdl")
public class ManageKategorijaExport1ManageKategorijaHttpService
    extends Service
{

    private final static URL MANAGEKATEGORIJAEXPORT1MANAGEKATEGORIJAHTTPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(foodratings.client.kategorija.ManageKategorijaExport1ManageKategorijaHttpService.class.getName());

    static {
        URL url = null;
        try {
            url = foodratings.client.kategorija.ManageKategorijaExport1ManageKategorijaHttpService.class.getResource("/WEB-INF/wsdl/KISFood_ManageKategorijaExport1.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/KISFood_ManageKategorijaExport1.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/KISFood_ManageKategorijaExport1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANAGEKATEGORIJAEXPORT1MANAGEKATEGORIJAHTTPSERVICE_WSDL_LOCATION = url;
    }

    public ManageKategorijaExport1ManageKategorijaHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageKategorijaExport1ManageKategorijaHttpService() {
        super(MANAGEKATEGORIJAEXPORT1MANAGEKATEGORIJAHTTPSERVICE_WSDL_LOCATION, new QName("http://KISFoodLib/ManageKategorija", "ManageKategorijaExport1_ManageKategorijaHttpService"));
    }

    /**
     * 
     * @return
     *     returns ManageKategorija
     */
    @WebEndpoint(name = "ManageKategorijaExport1_ManageKategorijaHttpPort")
    public ManageKategorija getManageKategorijaExport1ManageKategorijaHttpPort() {
        return super.getPort(new QName("http://KISFoodLib/ManageKategorija", "ManageKategorijaExport1_ManageKategorijaHttpPort"), ManageKategorija.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageKategorija
     */
    @WebEndpoint(name = "ManageKategorijaExport1_ManageKategorijaHttpPort")
    public ManageKategorija getManageKategorijaExport1ManageKategorijaHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://KISFoodLib/ManageKategorija", "ManageKategorijaExport1_ManageKategorijaHttpPort"), ManageKategorija.class, features);
    }

}
