//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client.proizvajalec;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the foodratings.client.proizvajalec package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: foodratings.client.proizvajalec
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteProizvajalecResponse }
     * 
     */
    public DeleteProizvajalecResponse createDeleteProizvajalecResponse() {
        return new DeleteProizvajalecResponse();
    }

    /**
     * Create an instance of {@link CreateProizvajalec }
     * 
     */
    public CreateProizvajalec createCreateProizvajalec() {
        return new CreateProizvajalec();
    }

    /**
     * Create an instance of {@link ListProizvajalecResponse }
     * 
     */
    public ListProizvajalecResponse createListProizvajalecResponse() {
        return new ListProizvajalecResponse();
    }

    /**
     * Create an instance of {@link Ocena }
     * 
     */
    public Ocena createOcena() {
        return new Ocena();
    }

    /**
     * Create an instance of {@link UpdateProizvajalec }
     * 
     */
    public UpdateProizvajalec createUpdateProizvajalec() {
        return new UpdateProizvajalec();
    }

    /**
     * Create an instance of {@link CreateProizvajalecResponse }
     * 
     */
    public CreateProizvajalecResponse createCreateProizvajalecResponse() {
        return new CreateProizvajalecResponse();
    }

    /**
     * Create an instance of {@link Proizvajalci }
     * 
     */
    public Proizvajalci createProizvajalci() {
        return new Proizvajalci();
    }

    /**
     * Create an instance of {@link UpdateProizvajalecResponse }
     * 
     */
    public UpdateProizvajalecResponse createUpdateProizvajalecResponse() {
        return new UpdateProizvajalecResponse();
    }

    /**
     * Create an instance of {@link ReadProizvajalec }
     * 
     */
    public ReadProizvajalec createReadProizvajalec() {
        return new ReadProizvajalec();
    }

    /**
     * Create an instance of {@link ReadProizvajalecResponse }
     * 
     */
    public ReadProizvajalecResponse createReadProizvajalecResponse() {
        return new ReadProizvajalecResponse();
    }

    /**
     * Create an instance of {@link DeleteProizvajalec }
     * 
     */
    public DeleteProizvajalec createDeleteProizvajalec() {
        return new DeleteProizvajalec();
    }

    /**
     * Create an instance of {@link Proizvajalec }
     * 
     */
    public Proizvajalec createProizvajalec() {
        return new Proizvajalec();
    }

    /**
     * Create an instance of {@link ListProizvajalec }
     * 
     */
    public ListProizvajalec createListProizvajalec() {
        return new ListProizvajalec();
    }

}
