//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package client.izdelek;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ManageIzdelekExport1_ManageIzdelekHttpService", targetNamespace = "http://KISFoodLib/ManageIzdelek", wsdlLocation = "WEB-INF/wsdl/KISFood_ManageIzdelekExport1.wsdl")
public class ManageIzdelekExport1ManageIzdelekHttpService
    extends Service
{

    private final static URL MANAGEIZDELEKEXPORT1MANAGEIZDELEKHTTPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.izdelek.ManageIzdelekExport1ManageIzdelekHttpService.class.getName());

    static {
        URL url = null;
        try {
            url = client.izdelek.ManageIzdelekExport1ManageIzdelekHttpService.class.getResource("/WEB-INF/wsdl/KISFood_ManageIzdelekExport1.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/KISFood_ManageIzdelekExport1.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/KISFood_ManageIzdelekExport1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANAGEIZDELEKEXPORT1MANAGEIZDELEKHTTPSERVICE_WSDL_LOCATION = url;
    }

    public ManageIzdelekExport1ManageIzdelekHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageIzdelekExport1ManageIzdelekHttpService() {
        super(MANAGEIZDELEKEXPORT1MANAGEIZDELEKHTTPSERVICE_WSDL_LOCATION, new QName("http://KISFoodLib/ManageIzdelek", "ManageIzdelekExport1_ManageIzdelekHttpService"));
    }

    /**
     * 
     * @return
     *     returns ManageIzdelek
     */
    @WebEndpoint(name = "ManageIzdelekExport1_ManageIzdelekHttpPort")
    public ManageIzdelek getManageIzdelekExport1ManageIzdelekHttpPort() {
        return super.getPort(new QName("http://KISFoodLib/ManageIzdelek", "ManageIzdelekExport1_ManageIzdelekHttpPort"), ManageIzdelek.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageIzdelek
     */
    @WebEndpoint(name = "ManageIzdelekExport1_ManageIzdelekHttpPort")
    public ManageIzdelek getManageIzdelekExport1ManageIzdelekHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://KISFoodLib/ManageIzdelek", "ManageIzdelekExport1_ManageIzdelekHttpPort"), ManageIzdelek.class, features);
    }

}
