//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package client.izdelek;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the client.izdelek package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: client.izdelek
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Proizvajalec }
     * 
     */
    public Proizvajalec createProizvajalec() {
        return new Proizvajalec();
    }

    /**
     * Create an instance of {@link ReadIzdelekResponse }
     * 
     */
    public ReadIzdelekResponse createReadIzdelekResponse() {
        return new ReadIzdelekResponse();
    }

    /**
     * Create an instance of {@link Izdelki }
     * 
     */
    public Izdelki createIzdelki() {
        return new Izdelki();
    }

    /**
     * Create an instance of {@link ReadIzdelek }
     * 
     */
    public ReadIzdelek createReadIzdelek() {
        return new ReadIzdelek();
    }

    /**
     * Create an instance of {@link Drzava }
     * 
     */
    public Drzava createDrzava() {
        return new Drzava();
    }

    /**
     * Create an instance of {@link Kategorija }
     * 
     */
    public Kategorija createKategorija() {
        return new Kategorija();
    }

    /**
     * Create an instance of {@link CreateIzdelekResponse }
     * 
     */
    public CreateIzdelekResponse createCreateIzdelekResponse() {
        return new CreateIzdelekResponse();
    }

    /**
     * Create an instance of {@link CreateIzdelek }
     * 
     */
    public CreateIzdelek createCreateIzdelek() {
        return new CreateIzdelek();
    }

    /**
     * Create an instance of {@link Izdelek }
     * 
     */
    public Izdelek createIzdelek() {
        return new Izdelek();
    }

    /**
     * Create an instance of {@link UpdateIzdelek }
     * 
     */
    public UpdateIzdelek createUpdateIzdelek() {
        return new UpdateIzdelek();
    }

    /**
     * Create an instance of {@link DeleteIzdelek }
     * 
     */
    public DeleteIzdelek createDeleteIzdelek() {
        return new DeleteIzdelek();
    }

    /**
     * Create an instance of {@link ListIzdelek }
     * 
     */
    public ListIzdelek createListIzdelek() {
        return new ListIzdelek();
    }

    /**
     * Create an instance of {@link ListIzdelekResponse }
     * 
     */
    public ListIzdelekResponse createListIzdelekResponse() {
        return new ListIzdelekResponse();
    }

    /**
     * Create an instance of {@link UpdateIzdelekResponse }
     * 
     */
    public UpdateIzdelekResponse createUpdateIzdelekResponse() {
        return new UpdateIzdelekResponse();
    }

    /**
     * Create an instance of {@link DeleteIzdelekResponse }
     * 
     */
    public DeleteIzdelekResponse createDeleteIzdelekResponse() {
        return new DeleteIzdelekResponse();
    }

}
