//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client.izdelek;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ManageIzdelek", targetNamespace = "http://KISFoodLib/ManageIzdelek")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManageIzdelek {


    /**
     * 
     * @param izdelek
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createIzdelek", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.CreateIzdelek")
    @ResponseWrapper(localName = "createIzdelekResponse", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.CreateIzdelekResponse")
    public Boolean createIzdelek(
        @WebParam(name = "izdelek", targetNamespace = "")
        Izdelek izdelek);

    /**
     * 
     * @param id
     * @return
     *     returns foodratings.client.izdelek.Izdelek
     */
    @WebMethod
    @WebResult(name = "izdelek", targetNamespace = "")
    @RequestWrapper(localName = "readIzdelek", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.ReadIzdelek")
    @ResponseWrapper(localName = "readIzdelekResponse", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.ReadIzdelekResponse")
    public Izdelek readIzdelek(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param izdelek
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateIzdelek", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.UpdateIzdelek")
    @ResponseWrapper(localName = "updateIzdelekResponse", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.UpdateIzdelekResponse")
    public Boolean updateIzdelek(
        @WebParam(name = "izdelek", targetNamespace = "")
        Izdelek izdelek);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteIzdelek", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.DeleteIzdelek")
    @ResponseWrapper(localName = "deleteIzdelekResponse", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.DeleteIzdelekResponse")
    public Boolean deleteIzdelek(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns foodratings.client.izdelek.Izdelki
     */
    @WebMethod
    @WebResult(name = "izdelki", targetNamespace = "")
    @RequestWrapper(localName = "listIzdelek", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.ListIzdelek")
    @ResponseWrapper(localName = "listIzdelekResponse", targetNamespace = "http://KISFoodLib/ManageIzdelek", className = "foodratings.client.izdelek.ListIzdelekResponse")
    public Izdelki listIzdelek();

}
