//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client.uporabnik;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ManageUporabnik", targetNamespace = "http://KISFoodLib/ManageUporabnik")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManageUporabnik {


    /**
     * 
     * @param uporabnik
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createUporabnik", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.CreateUporabnik")
    @ResponseWrapper(localName = "createUporabnikResponse", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.CreateUporabnikResponse")
    public Boolean createUporabnik(
        @WebParam(name = "uporabnik", targetNamespace = "")
        Uporabnik uporabnik);

    /**
     * 
     * @param id
     * @return
     *     returns foodratings.client.uporabnik.Uporabnik
     */
    @WebMethod
    @WebResult(name = "uporabnik", targetNamespace = "")
    @RequestWrapper(localName = "readUporabnik", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.ReadUporabnik")
    @ResponseWrapper(localName = "readUporabnikResponse", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.ReadUporabnikResponse")
    public Uporabnik readUporabnik(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param uporabnik
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateUporabnik", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.UpdateUporabnik")
    @ResponseWrapper(localName = "updateUporabnikResponse", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.UpdateUporabnikResponse")
    public Boolean updateUporabnik(
        @WebParam(name = "uporabnik", targetNamespace = "")
        Uporabnik uporabnik);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteUporabnik", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.DeleteUporabnik")
    @ResponseWrapper(localName = "deleteUporabnikResponse", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.DeleteUporabnikResponse")
    public Boolean deleteUporabnik(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns foodratings.client.uporabnik.Uporabniki
     */
    @WebMethod
    @WebResult(name = "uporabniki", targetNamespace = "")
    @RequestWrapper(localName = "listUporabnik", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.ListUporabnik")
    @ResponseWrapper(localName = "listUporabnikResponse", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.ListUporabnikResponse")
    public Uporabniki listUporabnik();

    /**
     * 
     * @param uporabnik
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "loginUporabnik", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.LoginUporabnik")
    @ResponseWrapper(localName = "loginUporabnikResponse", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.LoginUporabnikResponse")
    public Boolean loginUporabnik(
        @WebParam(name = "uporabnik", targetNamespace = "")
        Uporabnik uporabnik);

    /**
     * 
     * @param uporabnik
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "existsUporabnik", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.ExistsUporabnik")
    @ResponseWrapper(localName = "existsUporabnikResponse", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.ExistsUporabnikResponse")
    public Boolean existsUporabnik(
        @WebParam(name = "uporabnik", targetNamespace = "")
        Uporabnik uporabnik);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "isAdminUporabnik", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.IsAdminUporabnik")
    @ResponseWrapper(localName = "isAdminUporabnikResponse", targetNamespace = "http://KISFoodLib/ManageUporabnik", className = "foodratings.client.uporabnik.IsAdminUporabnikResponse")
    public Boolean isAdminUporabnik(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

}
