//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client.uporabnik;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ManageUporabnikExport1_ManageUporabnikHttpService", targetNamespace = "http://KISFoodLib/ManageUporabnik", wsdlLocation = "WEB-INF/wsdl/KISFood_ManageUporabnikExport1.wsdl")
public class ManageUporabnikExport1ManageUporabnikHttpService
    extends Service
{

    private final static URL MANAGEUPORABNIKEXPORT1MANAGEUPORABNIKHTTPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(foodratings.client.uporabnik.ManageUporabnikExport1ManageUporabnikHttpService.class.getName());

    static {
        URL url = null;
        try {
            url = foodratings.client.uporabnik.ManageUporabnikExport1ManageUporabnikHttpService.class.getResource("/WEB-INF/wsdl/KISFood_ManageUporabnikExport1.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/KISFood_ManageUporabnikExport1.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/KISFood_ManageUporabnikExport1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANAGEUPORABNIKEXPORT1MANAGEUPORABNIKHTTPSERVICE_WSDL_LOCATION = url;
    }

    public ManageUporabnikExport1ManageUporabnikHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageUporabnikExport1ManageUporabnikHttpService() {
        super(MANAGEUPORABNIKEXPORT1MANAGEUPORABNIKHTTPSERVICE_WSDL_LOCATION, new QName("http://KISFoodLib/ManageUporabnik", "ManageUporabnikExport1_ManageUporabnikHttpService"));
    }

    /**
     * 
     * @return
     *     returns ManageUporabnik
     */
    @WebEndpoint(name = "ManageUporabnikExport1_ManageUporabnikHttpPort")
    public ManageUporabnik getManageUporabnikExport1ManageUporabnikHttpPort() {
        return super.getPort(new QName("http://KISFoodLib/ManageUporabnik", "ManageUporabnikExport1_ManageUporabnikHttpPort"), ManageUporabnik.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageUporabnik
     */
    @WebEndpoint(name = "ManageUporabnikExport1_ManageUporabnikHttpPort")
    public ManageUporabnik getManageUporabnikExport1ManageUporabnikHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://KISFoodLib/ManageUporabnik", "ManageUporabnikExport1_ManageUporabnikHttpPort"), ManageUporabnik.class, features);
    }

}
