//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client.uporabnik;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the foodratings.client.uporabnik package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: foodratings.client.uporabnik
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateUporabnikResponse }
     * 
     */
    public CreateUporabnikResponse createCreateUporabnikResponse() {
        return new CreateUporabnikResponse();
    }

    /**
     * Create an instance of {@link LoginUporabnikResponse }
     * 
     */
    public LoginUporabnikResponse createLoginUporabnikResponse() {
        return new LoginUporabnikResponse();
    }

    /**
     * Create an instance of {@link ListUporabnik }
     * 
     */
    public ListUporabnik createListUporabnik() {
        return new ListUporabnik();
    }

    /**
     * Create an instance of {@link ReadUporabnikResponse }
     * 
     */
    public ReadUporabnikResponse createReadUporabnikResponse() {
        return new ReadUporabnikResponse();
    }

    /**
     * Create an instance of {@link UpdateUporabnik }
     * 
     */
    public UpdateUporabnik createUpdateUporabnik() {
        return new UpdateUporabnik();
    }

    /**
     * Create an instance of {@link UpdateUporabnikResponse }
     * 
     */
    public UpdateUporabnikResponse createUpdateUporabnikResponse() {
        return new UpdateUporabnikResponse();
    }

    /**
     * Create an instance of {@link LoginUporabnik }
     * 
     */
    public LoginUporabnik createLoginUporabnik() {
        return new LoginUporabnik();
    }

    /**
     * Create an instance of {@link ExistsUporabnikResponse }
     * 
     */
    public ExistsUporabnikResponse createExistsUporabnikResponse() {
        return new ExistsUporabnikResponse();
    }

    /**
     * Create an instance of {@link DeleteUporabnik }
     * 
     */
    public DeleteUporabnik createDeleteUporabnik() {
        return new DeleteUporabnik();
    }

    /**
     * Create an instance of {@link ReadUporabnik }
     * 
     */
    public ReadUporabnik createReadUporabnik() {
        return new ReadUporabnik();
    }

    /**
     * Create an instance of {@link IsAdminUporabnikResponse }
     * 
     */
    public IsAdminUporabnikResponse createIsAdminUporabnikResponse() {
        return new IsAdminUporabnikResponse();
    }

    /**
     * Create an instance of {@link ListUporabnikResponse }
     * 
     */
    public ListUporabnikResponse createListUporabnikResponse() {
        return new ListUporabnikResponse();
    }

    /**
     * Create an instance of {@link Uporabniki }
     * 
     */
    public Uporabniki createUporabniki() {
        return new Uporabniki();
    }

    /**
     * Create an instance of {@link ExistsUporabnik }
     * 
     */
    public ExistsUporabnik createExistsUporabnik() {
        return new ExistsUporabnik();
    }

    /**
     * Create an instance of {@link IsAdminUporabnik }
     * 
     */
    public IsAdminUporabnik createIsAdminUporabnik() {
        return new IsAdminUporabnik();
    }

    /**
     * Create an instance of {@link CreateUporabnik }
     * 
     */
    public CreateUporabnik createCreateUporabnik() {
        return new CreateUporabnik();
    }

    /**
     * Create an instance of {@link DeleteUporabnikResponse }
     * 
     */
    public DeleteUporabnikResponse createDeleteUporabnikResponse() {
        return new DeleteUporabnikResponse();
    }

    /**
     * Create an instance of {@link Uporabnik }
     * 
     */
    public Uporabnik createUporabnik() {
        return new Uporabnik();
    }

}
