//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "DataManagerExport1_DataManagerHttpService", targetNamespace = "http://KISFoodLib/DataManager", wsdlLocation = "WEB-INF/wsdl/KISFood_DataManagerExport1.wsdl")
public class DataManagerExport1DataManagerHttpService
    extends Service
{

    private final static URL DATAMANAGEREXPORT1DATAMANAGERHTTPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(foodratings.client.DataManagerExport1DataManagerHttpService.class.getName());

    static {
        URL url = null;
        try {
            url = foodratings.client.DataManagerExport1DataManagerHttpService.class.getResource("/WEB-INF/wsdl/KISFood_DataManagerExport1.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/KISFood_DataManagerExport1.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/KISFood_DataManagerExport1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATAMANAGEREXPORT1DATAMANAGERHTTPSERVICE_WSDL_LOCATION = url;
    }

    public DataManagerExport1DataManagerHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataManagerExport1DataManagerHttpService() {
        super(DATAMANAGEREXPORT1DATAMANAGERHTTPSERVICE_WSDL_LOCATION, new QName("http://KISFoodLib/DataManager", "DataManagerExport1_DataManagerHttpService"));
    }

    /**
     * 
     * @return
     *     returns DataManager
     */
    @WebEndpoint(name = "DataManagerExport1_DataManagerHttpPort")
    public DataManager getDataManagerExport1DataManagerHttpPort() {
        return super.getPort(new QName("http://KISFoodLib/DataManager", "DataManagerExport1_DataManagerHttpPort"), DataManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataManager
     */
    @WebEndpoint(name = "DataManagerExport1_DataManagerHttpPort")
    public DataManager getDataManagerExport1DataManagerHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://KISFoodLib/DataManager", "DataManagerExport1_DataManagerHttpPort"), DataManager.class, features);
    }

}
