//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "DataManager", targetNamespace = "http://KISFoodLib/DataManager")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataManager {


    /**
     * 
     * @param drzava
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createDrzava", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateDrzava")
    @ResponseWrapper(localName = "createDrzavaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateDrzavaResponse")
    public Boolean createDrzava(
        @WebParam(name = "drzava", targetNamespace = "")
        Drzava drzava);

    /**
     * 
     * @param id
     * @return
     *     returns foodratings.client.Drzava
     */
    @WebMethod
    @WebResult(name = "drzava", targetNamespace = "")
    @RequestWrapper(localName = "readDrzava", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadDrzava")
    @ResponseWrapper(localName = "readDrzavaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadDrzavaResponse")
    public Drzava readDrzava(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param drzava
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateDrzava", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateDrzava")
    @ResponseWrapper(localName = "updateDrzavaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateDrzavaResponse")
    public Boolean updateDrzava(
        @WebParam(name = "drzava", targetNamespace = "")
        Drzava drzava);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteDrzava", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteDrzava")
    @ResponseWrapper(localName = "deleteDrzavaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteDrzavaResponse")
    public Boolean deleteDrzava(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns foodratings.client.Drzave
     */
    @WebMethod
    @WebResult(name = "drzave", targetNamespace = "")
    @RequestWrapper(localName = "listDrzava", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListDrzava")
    @ResponseWrapper(localName = "listDrzavaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListDrzavaResponse")
    public Drzave listDrzava();

    /**
     * 
     * @param izdelek
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createIzdelek", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateIzdelek")
    @ResponseWrapper(localName = "createIzdelekResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateIzdelekResponse")
    public Boolean createIzdelek(
        @WebParam(name = "izdelek", targetNamespace = "")
        Izdelek izdelek);

    /**
     * 
     * @param id
     * @return
     *     returns foodratings.client.Izdelek
     */
    @WebMethod
    @WebResult(name = "izdelek", targetNamespace = "")
    @RequestWrapper(localName = "readIzdelek", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadIzdelek")
    @ResponseWrapper(localName = "readIzdelekResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadIzdelekResponse")
    public Izdelek readIzdelek(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param izdelek
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateIzdelek", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateIzdelek")
    @ResponseWrapper(localName = "updateIzdelekResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateIzdelekResponse")
    public Boolean updateIzdelek(
        @WebParam(name = "izdelek", targetNamespace = "")
        Izdelek izdelek);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteIzdelek", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteIzdelek")
    @ResponseWrapper(localName = "deleteIzdelekResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteIzdelekResponse")
    public Boolean deleteIzdelek(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns foodratings.client.Izdelki
     */
    @WebMethod
    @WebResult(name = "izdelki", targetNamespace = "")
    @RequestWrapper(localName = "listIzdelek", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListIzdelek")
    @ResponseWrapper(localName = "listIzdelekResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListIzdelekResponse")
    public Izdelki listIzdelek();

    /**
     * 
     * @param engName
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getKalorijeIzdelek", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.GetKalorijeIzdelek")
    @ResponseWrapper(localName = "getKalorijeIzdelekResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.GetKalorijeIzdelekResponse")
    public Double getKalorijeIzdelek(
        @WebParam(name = "engName", targetNamespace = "")
        String engName);

    /**
     * 
     * @param kategorija
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createKategorija", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateKategorija")
    @ResponseWrapper(localName = "createKategorijaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateKategorijaResponse")
    public Boolean createKategorija(
        @WebParam(name = "kategorija", targetNamespace = "")
        Kategorija kategorija);

    /**
     * 
     * @param id
     * @return
     *     returns foodratings.client.Kategorija
     */
    @WebMethod
    @WebResult(name = "kategorija", targetNamespace = "")
    @RequestWrapper(localName = "readKategorija", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadKategorija")
    @ResponseWrapper(localName = "readKategorijaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadKategorijaResponse")
    public Kategorija readKategorija(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param kategorija
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateKategorija", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateKategorija")
    @ResponseWrapper(localName = "updateKategorijaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateKategorijaResponse")
    public Boolean updateKategorija(
        @WebParam(name = "kategorija", targetNamespace = "")
        Kategorija kategorija);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteKategorija", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteKategorija")
    @ResponseWrapper(localName = "deleteKategorijaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteKategorijaResponse")
    public Boolean deleteKategorija(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns foodratings.client.Kategorije
     */
    @WebMethod
    @WebResult(name = "kategorije", targetNamespace = "")
    @RequestWrapper(localName = "listKategorija", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListKategorija")
    @ResponseWrapper(localName = "listKategorijaResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListKategorijaResponse")
    public Kategorije listKategorija();

    /**
     * 
     * @param proizvajalec
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createProizvajalec", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateProizvajalec")
    @ResponseWrapper(localName = "createProizvajalecResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateProizvajalecResponse")
    public Boolean createProizvajalec(
        @WebParam(name = "proizvajalec", targetNamespace = "")
        Proizvajalec proizvajalec);

    /**
     * 
     * @param id
     * @return
     *     returns foodratings.client.Proizvajalec
     */
    @WebMethod
    @WebResult(name = "proizvajalec", targetNamespace = "")
    @RequestWrapper(localName = "readProizvajalec", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadProizvajalec")
    @ResponseWrapper(localName = "readProizvajalecResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadProizvajalecResponse")
    public Proizvajalec readProizvajalec(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param proizvajalec
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateProizvajalec", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateProizvajalec")
    @ResponseWrapper(localName = "updateProizvajalecResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateProizvajalecResponse")
    public Boolean updateProizvajalec(
        @WebParam(name = "proizvajalec", targetNamespace = "")
        Proizvajalec proizvajalec);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteProizvajalec", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteProizvajalec")
    @ResponseWrapper(localName = "deleteProizvajalecResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteProizvajalecResponse")
    public Boolean deleteProizvajalec(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns foodratings.client.Proizvajalci
     */
    @WebMethod
    @WebResult(name = "proizvajalci", targetNamespace = "")
    @RequestWrapper(localName = "listProizvajalec", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListProizvajalec")
    @ResponseWrapper(localName = "listProizvajalecResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListProizvajalecResponse")
    public Proizvajalci listProizvajalec();

    /**
     * 
     * @param uporabnik
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createUporabnik", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateUporabnik")
    @ResponseWrapper(localName = "createUporabnikResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.CreateUporabnikResponse")
    public Boolean createUporabnik(
        @WebParam(name = "uporabnik", targetNamespace = "")
        Uporabnik uporabnik);

    /**
     * 
     * @param id
     * @return
     *     returns foodratings.client.Uporabnik
     */
    @WebMethod
    @WebResult(name = "uporabnik", targetNamespace = "")
    @RequestWrapper(localName = "readUporabnik", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadUporabnik")
    @ResponseWrapper(localName = "readUporabnikResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ReadUporabnikResponse")
    public Uporabnik readUporabnik(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param uporabnik
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateUporabnik", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateUporabnik")
    @ResponseWrapper(localName = "updateUporabnikResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.UpdateUporabnikResponse")
    public Boolean updateUporabnik(
        @WebParam(name = "uporabnik", targetNamespace = "")
        Uporabnik uporabnik);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteUporabnik", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteUporabnik")
    @ResponseWrapper(localName = "deleteUporabnikResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.DeleteUporabnikResponse")
    public Boolean deleteUporabnik(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns foodratings.client.Uporabniki
     */
    @WebMethod
    @WebResult(name = "uporabniki", targetNamespace = "")
    @RequestWrapper(localName = "listUporabnik", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListUporabnik")
    @ResponseWrapper(localName = "listUporabnikResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ListUporabnikResponse")
    public Uporabniki listUporabnik();

    /**
     * 
     * @param uporabnik
     * @return
     *     returns foodratings.client.Uporabnik
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "loginUporabnik", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.LoginUporabnik")
    @ResponseWrapper(localName = "loginUporabnikResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.LoginUporabnikResponse")
    public Uporabnik loginUporabnik(
        @WebParam(name = "uporabnik", targetNamespace = "")
        Uporabnik uporabnik);

    /**
     * 
     * @param uporabnik
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "existsUporabnik", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ExistsUporabnik")
    @ResponseWrapper(localName = "existsUporabnikResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.ExistsUporabnikResponse")
    public Boolean existsUporabnik(
        @WebParam(name = "uporabnik", targetNamespace = "")
        Uporabnik uporabnik);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "isAdminUporabnik", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.IsAdminUporabnik")
    @ResponseWrapper(localName = "isAdminUporabnikResponse", targetNamespace = "http://KISFoodLib/DataManager", className = "foodratings.client.IsAdminUporabnikResponse")
    public Boolean isAdminUporabnik(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

}
