//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kategorije" type="{http://KISFoodLib}Kategorije"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kategorije"
})
@XmlRootElement(name = "listKategorijaResponse")
public class ListKategorijaResponse {

    @XmlElement(required = true, nillable = true)
    protected Kategorije kategorije;

    /**
     * Gets the value of the kategorije property.
     * 
     * @return
     *     possible object is
     *     {@link Kategorije }
     *     
     */
    public Kategorije getKategorije() {
        return kategorije;
    }

    /**
     * Sets the value of the kategorije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kategorije }
     *     
     */
    public void setKategorije(Kategorije value) {
        this.kategorije = value;
    }

}
