//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the foodratings.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: foodratings.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateIzdelek }
     * 
     */
    public UpdateIzdelek createUpdateIzdelek() {
        return new UpdateIzdelek();
    }

    /**
     * Create an instance of {@link CreateKategorija }
     * 
     */
    public CreateKategorija createCreateKategorija() {
        return new CreateKategorija();
    }

    /**
     * Create an instance of {@link ListKategorijaResponse }
     * 
     */
    public ListKategorijaResponse createListKategorijaResponse() {
        return new ListKategorijaResponse();
    }

    /**
     * Create an instance of {@link DeleteKategorijaResponse }
     * 
     */
    public DeleteKategorijaResponse createDeleteKategorijaResponse() {
        return new DeleteKategorijaResponse();
    }

    /**
     * Create an instance of {@link LoginUporabnik }
     * 
     */
    public LoginUporabnik createLoginUporabnik() {
        return new LoginUporabnik();
    }

    /**
     * Create an instance of {@link ListKategorija }
     * 
     */
    public ListKategorija createListKategorija() {
        return new ListKategorija();
    }

    /**
     * Create an instance of {@link UpdateProizvajalecResponse }
     * 
     */
    public UpdateProizvajalecResponse createUpdateProizvajalecResponse() {
        return new UpdateProizvajalecResponse();
    }

    /**
     * Create an instance of {@link UpdateDrzava }
     * 
     */
    public UpdateDrzava createUpdateDrzava() {
        return new UpdateDrzava();
    }

    /**
     * Create an instance of {@link ReadProizvajalec }
     * 
     */
    public ReadProizvajalec createReadProizvajalec() {
        return new ReadProizvajalec();
    }

    /**
     * Create an instance of {@link ReadIzdelekResponse }
     * 
     */
    public ReadIzdelekResponse createReadIzdelekResponse() {
        return new ReadIzdelekResponse();
    }

    /**
     * Create an instance of {@link ReadKategorijaResponse }
     * 
     */
    public ReadKategorijaResponse createReadKategorijaResponse() {
        return new ReadKategorijaResponse();
    }

    /**
     * Create an instance of {@link ReadUporabnikResponse }
     * 
     */
    public ReadUporabnikResponse createReadUporabnikResponse() {
        return new ReadUporabnikResponse();
    }

    /**
     * Create an instance of {@link UpdateIzdelekResponse }
     * 
     */
    public UpdateIzdelekResponse createUpdateIzdelekResponse() {
        return new UpdateIzdelekResponse();
    }

    /**
     * Create an instance of {@link IsAdminUporabnikResponse }
     * 
     */
    public IsAdminUporabnikResponse createIsAdminUporabnikResponse() {
        return new IsAdminUporabnikResponse();
    }

    /**
     * Create an instance of {@link CreateUporabnik }
     * 
     */
    public CreateUporabnik createCreateUporabnik() {
        return new CreateUporabnik();
    }

    /**
     * Create an instance of {@link ListUporabnik }
     * 
     */
    public ListUporabnik createListUporabnik() {
        return new ListUporabnik();
    }

    /**
     * Create an instance of {@link DeleteIzdelek }
     * 
     */
    public DeleteIzdelek createDeleteIzdelek() {
        return new DeleteIzdelek();
    }

    /**
     * Create an instance of {@link Izdelek }
     * 
     */
    public Izdelek createIzdelek() {
        return new Izdelek();
    }

    /**
     * Create an instance of {@link Uporabnik }
     * 
     */
    public Uporabnik createUporabnik() {
        return new Uporabnik();
    }

    /**
     * Create an instance of {@link DeleteDrzava }
     * 
     */
    public DeleteDrzava createDeleteDrzava() {
        return new DeleteDrzava();
    }

    /**
     * Create an instance of {@link ReadUporabnik }
     * 
     */
    public ReadUporabnik createReadUporabnik() {
        return new ReadUporabnik();
    }

    /**
     * Create an instance of {@link ListProizvajalecResponse }
     * 
     */
    public ListProizvajalecResponse createListProizvajalecResponse() {
        return new ListProizvajalecResponse();
    }

    /**
     * Create an instance of {@link IsAdminUporabnik }
     * 
     */
    public IsAdminUporabnik createIsAdminUporabnik() {
        return new IsAdminUporabnik();
    }

    /**
     * Create an instance of {@link ReadDrzavaResponse }
     * 
     */
    public ReadDrzavaResponse createReadDrzavaResponse() {
        return new ReadDrzavaResponse();
    }

    /**
     * Create an instance of {@link DeleteUporabnikResponse }
     * 
     */
    public DeleteUporabnikResponse createDeleteUporabnikResponse() {
        return new DeleteUporabnikResponse();
    }

    /**
     * Create an instance of {@link UpdateKategorijaResponse }
     * 
     */
    public UpdateKategorijaResponse createUpdateKategorijaResponse() {
        return new UpdateKategorijaResponse();
    }

    /**
     * Create an instance of {@link Kategorije }
     * 
     */
    public Kategorije createKategorije() {
        return new Kategorije();
    }

    /**
     * Create an instance of {@link ExistsUporabnik }
     * 
     */
    public ExistsUporabnik createExistsUporabnik() {
        return new ExistsUporabnik();
    }

    /**
     * Create an instance of {@link UpdateUporabnikResponse }
     * 
     */
    public UpdateUporabnikResponse createUpdateUporabnikResponse() {
        return new UpdateUporabnikResponse();
    }

    /**
     * Create an instance of {@link Drzava }
     * 
     */
    public Drzava createDrzava() {
        return new Drzava();
    }

    /**
     * Create an instance of {@link Kategorija }
     * 
     */
    public Kategorija createKategorija() {
        return new Kategorija();
    }

    /**
     * Create an instance of {@link DeleteIzdelekResponse }
     * 
     */
    public DeleteIzdelekResponse createDeleteIzdelekResponse() {
        return new DeleteIzdelekResponse();
    }

    /**
     * Create an instance of {@link DeleteProizvajalec }
     * 
     */
    public DeleteProizvajalec createDeleteProizvajalec() {
        return new DeleteProizvajalec();
    }

    /**
     * Create an instance of {@link CreateKategorijaResponse }
     * 
     */
    public CreateKategorijaResponse createCreateKategorijaResponse() {
        return new CreateKategorijaResponse();
    }

    /**
     * Create an instance of {@link DeleteProizvajalecResponse }
     * 
     */
    public DeleteProizvajalecResponse createDeleteProizvajalecResponse() {
        return new DeleteProizvajalecResponse();
    }

    /**
     * Create an instance of {@link UpdateUporabnik }
     * 
     */
    public UpdateUporabnik createUpdateUporabnik() {
        return new UpdateUporabnik();
    }

    /**
     * Create an instance of {@link Proizvajalci }
     * 
     */
    public Proizvajalci createProizvajalci() {
        return new Proizvajalci();
    }

    /**
     * Create an instance of {@link DeleteDrzavaResponse }
     * 
     */
    public DeleteDrzavaResponse createDeleteDrzavaResponse() {
        return new DeleteDrzavaResponse();
    }

    /**
     * Create an instance of {@link ReadDrzava }
     * 
     */
    public ReadDrzava createReadDrzava() {
        return new ReadDrzava();
    }

    /**
     * Create an instance of {@link DeleteUporabnik }
     * 
     */
    public DeleteUporabnik createDeleteUporabnik() {
        return new DeleteUporabnik();
    }

    /**
     * Create an instance of {@link ListIzdelek }
     * 
     */
    public ListIzdelek createListIzdelek() {
        return new ListIzdelek();
    }

    /**
     * Create an instance of {@link LoginUporabnikResponse }
     * 
     */
    public LoginUporabnikResponse createLoginUporabnikResponse() {
        return new LoginUporabnikResponse();
    }

    /**
     * Create an instance of {@link CreateIzdelek }
     * 
     */
    public CreateIzdelek createCreateIzdelek() {
        return new CreateIzdelek();
    }

    /**
     * Create an instance of {@link ListDrzava }
     * 
     */
    public ListDrzava createListDrzava() {
        return new ListDrzava();
    }

    /**
     * Create an instance of {@link UpdateProizvajalec }
     * 
     */
    public UpdateProizvajalec createUpdateProizvajalec() {
        return new UpdateProizvajalec();
    }

    /**
     * Create an instance of {@link ListProizvajalec }
     * 
     */
    public ListProizvajalec createListProizvajalec() {
        return new ListProizvajalec();
    }

    /**
     * Create an instance of {@link DeleteKategorija }
     * 
     */
    public DeleteKategorija createDeleteKategorija() {
        return new DeleteKategorija();
    }

    /**
     * Create an instance of {@link CreateIzdelekResponse }
     * 
     */
    public CreateIzdelekResponse createCreateIzdelekResponse() {
        return new CreateIzdelekResponse();
    }

    /**
     * Create an instance of {@link Ocena }
     * 
     */
    public Ocena createOcena() {
        return new Ocena();
    }

    /**
     * Create an instance of {@link ReadIzdelek }
     * 
     */
    public ReadIzdelek createReadIzdelek() {
        return new ReadIzdelek();
    }

    /**
     * Create an instance of {@link ReadKategorija }
     * 
     */
    public ReadKategorija createReadKategorija() {
        return new ReadKategorija();
    }

    /**
     * Create an instance of {@link ListUporabnikResponse }
     * 
     */
    public ListUporabnikResponse createListUporabnikResponse() {
        return new ListUporabnikResponse();
    }

    /**
     * Create an instance of {@link CreateProizvajalec }
     * 
     */
    public CreateProizvajalec createCreateProizvajalec() {
        return new CreateProizvajalec();
    }

    /**
     * Create an instance of {@link CreateDrzavaResponse }
     * 
     */
    public CreateDrzavaResponse createCreateDrzavaResponse() {
        return new CreateDrzavaResponse();
    }

    /**
     * Create an instance of {@link ListIzdelekResponse }
     * 
     */
    public ListIzdelekResponse createListIzdelekResponse() {
        return new ListIzdelekResponse();
    }

    /**
     * Create an instance of {@link ReadProizvajalecResponse }
     * 
     */
    public ReadProizvajalecResponse createReadProizvajalecResponse() {
        return new ReadProizvajalecResponse();
    }

    /**
     * Create an instance of {@link UpdateDrzavaResponse }
     * 
     */
    public UpdateDrzavaResponse createUpdateDrzavaResponse() {
        return new UpdateDrzavaResponse();
    }

    /**
     * Create an instance of {@link Izdelki }
     * 
     */
    public Izdelki createIzdelki() {
        return new Izdelki();
    }

    /**
     * Create an instance of {@link ExistsUporabnikResponse }
     * 
     */
    public ExistsUporabnikResponse createExistsUporabnikResponse() {
        return new ExistsUporabnikResponse();
    }

    /**
     * Create an instance of {@link CreateUporabnikResponse }
     * 
     */
    public CreateUporabnikResponse createCreateUporabnikResponse() {
        return new CreateUporabnikResponse();
    }

    /**
     * Create an instance of {@link CreateProizvajalecResponse }
     * 
     */
    public CreateProizvajalecResponse createCreateProizvajalecResponse() {
        return new CreateProizvajalecResponse();
    }

    /**
     * Create an instance of {@link ListDrzavaResponse }
     * 
     */
    public ListDrzavaResponse createListDrzavaResponse() {
        return new ListDrzavaResponse();
    }

    /**
     * Create an instance of {@link Proizvajalec }
     * 
     */
    public Proizvajalec createProizvajalec() {
        return new Proizvajalec();
    }

    /**
     * Create an instance of {@link UpdateKategorija }
     * 
     */
    public UpdateKategorija createUpdateKategorija() {
        return new UpdateKategorija();
    }

    /**
     * Create an instance of {@link CreateDrzava }
     * 
     */
    public CreateDrzava createCreateDrzava() {
        return new CreateDrzava();
    }

    /**
     * Create an instance of {@link Uporabniki }
     * 
     */
    public Uporabniki createUporabniki() {
        return new Uporabniki();
    }

    /**
     * Create an instance of {@link Drzave }
     * 
     */
    public Drzave createDrzave() {
        return new Drzave();
    }

}
