//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package client.kategorija;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the client.kategorija package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: client.kategorija
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateKategorija }
     * 
     */
    public UpdateKategorija createUpdateKategorija() {
        return new UpdateKategorija();
    }

    /**
     * Create an instance of {@link ReadKategorija }
     * 
     */
    public ReadKategorija createReadKategorija() {
        return new ReadKategorija();
    }

    /**
     * Create an instance of {@link ReadKategorijaResponse }
     * 
     */
    public ReadKategorijaResponse createReadKategorijaResponse() {
        return new ReadKategorijaResponse();
    }

    /**
     * Create an instance of {@link DeleteKategorija }
     * 
     */
    public DeleteKategorija createDeleteKategorija() {
        return new DeleteKategorija();
    }

    /**
     * Create an instance of {@link Kategorija }
     * 
     */
    public Kategorija createKategorija() {
        return new Kategorija();
    }

    /**
     * Create an instance of {@link ListKategorija }
     * 
     */
    public ListKategorija createListKategorija() {
        return new ListKategorija();
    }

    /**
     * Create an instance of {@link CreateKategorijaResponse }
     * 
     */
    public CreateKategorijaResponse createCreateKategorijaResponse() {
        return new CreateKategorijaResponse();
    }

    /**
     * Create an instance of {@link CreateKategorija }
     * 
     */
    public CreateKategorija createCreateKategorija() {
        return new CreateKategorija();
    }

    /**
     * Create an instance of {@link DeleteKategorijaResponse }
     * 
     */
    public DeleteKategorijaResponse createDeleteKategorijaResponse() {
        return new DeleteKategorijaResponse();
    }

    /**
     * Create an instance of {@link ListKategorijaResponse }
     * 
     */
    public ListKategorijaResponse createListKategorijaResponse() {
        return new ListKategorijaResponse();
    }

    /**
     * Create an instance of {@link Kategorije }
     * 
     */
    public Kategorije createKategorije() {
        return new Kategorije();
    }

    /**
     * Create an instance of {@link UpdateKategorijaResponse }
     * 
     */
    public UpdateKategorijaResponse createUpdateKategorijaResponse() {
        return new UpdateKategorijaResponse();
    }

}
