//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client.drzava;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ManageDrzava", targetNamespace = "http://KISFoodLib/ManageDrzava")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManageDrzava {


    /**
     * 
     * @param drzava
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createDrzava", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.CreateDrzava")
    @ResponseWrapper(localName = "createDrzavaResponse", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.CreateDrzavaResponse")
    public Boolean createDrzava(
        @WebParam(name = "drzava", targetNamespace = "")
        Drzava drzava);

    /**
     * 
     * @param id
     * @return
     *     returns foodratings.client.drzava.Drzava
     */
    @WebMethod
    @WebResult(name = "drzava", targetNamespace = "")
    @RequestWrapper(localName = "readDrzava", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.ReadDrzava")
    @ResponseWrapper(localName = "readDrzavaResponse", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.ReadDrzavaResponse")
    public Drzava readDrzava(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param drzava
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateDrzava", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.UpdateDrzava")
    @ResponseWrapper(localName = "updateDrzavaResponse", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.UpdateDrzavaResponse")
    public Boolean updateDrzava(
        @WebParam(name = "drzava", targetNamespace = "")
        Drzava drzava);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteDrzava", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.DeleteDrzava")
    @ResponseWrapper(localName = "deleteDrzavaResponse", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.DeleteDrzavaResponse")
    public Boolean deleteDrzava(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns foodratings.client.drzava.Drzave
     */
    @WebMethod
    @WebResult(name = "drzave", targetNamespace = "")
    @RequestWrapper(localName = "listDrzava", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.ListDrzava")
    @ResponseWrapper(localName = "listDrzavaResponse", targetNamespace = "http://KISFoodLib/ManageDrzava", className = "foodratings.client.drzava.ListDrzavaResponse")
    public Drzave listDrzava();

}
