//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package foodratings.client.drzava;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the foodratings.client.drzava package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: foodratings.client.drzava
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReadDrzavaResponse }
     * 
     */
    public ReadDrzavaResponse createReadDrzavaResponse() {
        return new ReadDrzavaResponse();
    }

    /**
     * Create an instance of {@link DeleteDrzava }
     * 
     */
    public DeleteDrzava createDeleteDrzava() {
        return new DeleteDrzava();
    }

    /**
     * Create an instance of {@link ListDrzavaResponse }
     * 
     */
    public ListDrzavaResponse createListDrzavaResponse() {
        return new ListDrzavaResponse();
    }

    /**
     * Create an instance of {@link DeleteDrzavaResponse }
     * 
     */
    public DeleteDrzavaResponse createDeleteDrzavaResponse() {
        return new DeleteDrzavaResponse();
    }

    /**
     * Create an instance of {@link CreateDrzava }
     * 
     */
    public CreateDrzava createCreateDrzava() {
        return new CreateDrzava();
    }

    /**
     * Create an instance of {@link CreateDrzavaResponse }
     * 
     */
    public CreateDrzavaResponse createCreateDrzavaResponse() {
        return new CreateDrzavaResponse();
    }

    /**
     * Create an instance of {@link Drzava }
     * 
     */
    public Drzava createDrzava() {
        return new Drzava();
    }

    /**
     * Create an instance of {@link Ocena }
     * 
     */
    public Ocena createOcena() {
        return new Ocena();
    }

    /**
     * Create an instance of {@link Drzave }
     * 
     */
    public Drzave createDrzave() {
        return new Drzave();
    }

    /**
     * Create an instance of {@link UpdateDrzava }
     * 
     */
    public UpdateDrzava createUpdateDrzava() {
        return new UpdateDrzava();
    }

    /**
     * Create an instance of {@link UpdateDrzavaResponse }
     * 
     */
    public UpdateDrzavaResponse createUpdateDrzavaResponse() {
        return new UpdateDrzavaResponse();
    }

    /**
     * Create an instance of {@link ListDrzava }
     * 
     */
    public ListDrzava createListDrzava() {
        return new ListDrzava();
    }

    /**
     * Create an instance of {@link ReadDrzava }
     * 
     */
    public ReadDrzava createReadDrzava() {
        return new ReadDrzava();
    }

}
